-- 테스트용 테이블 생성
CREATE TABLE TB_SUBWAY_STATN_TMP (
    SUBWAY_STATN_NO CHAR(6) NOT NULL,
    LN_NM VARCHAR2(50) NOT NULL,
    STATN_NM VARCHAR2(50) NOT NULL,
    -- 기본키 제약조건 설정
    CONSTRAINT PK_TB_SUBWAY_STATN_TMP PRIMARY KEY(SUBWAY_STATN_NO)
);
-- 신규 데이터 입력
INSERT INTO TB_SUBWAY_STATN_TMP T (
        T.SUBWAY_STATN_NO,
        T.LN_NM,
        T.STATN_NM
    )
VALUES ('000032', '2호선', '강남');
COMMIT;
-- 입력한 데이터 조회 
SELECT A.SUBWAY_STATN_NO,
    A.LN_NM,
    A.STATN_NM
FROM TB_SUBWAY_STATN_TMP A
WHERE A.STATN_NM = '강남';
-- 데이터 수정
UPDATE TB_SUBWAY_STATN_TMP A
SET A.LN_NM = '녹색선',
    A.STATN_NM = '강남스타일'
WHERE A.SUBWAY_STATN_NO = '000032';
-- 데이터 삭제
DELETE FROM TB_SUBWAY_STATN_TMP A
WHERE A.SUBWAY_STATN_NO = '000032';
COMMIT;