-- SELECT문
SELECT A.INDUTY_CL_CD,
    A.INDUTY_CL_NM,
    A.INDUTY_CL_SE_CD,
    NVL(A.UPPER_INDUTY_CL_CD, '(Null)') AS UPPER_INDEUTY_CL_CD
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_SE_CD = 'ICS001';
-- DISTINCT : SELECT 중복 행 제거
SELECT DISTINCT A.INDUTY_CL_SE_CD
FROM TB_INDUTY_CL AS;
-- DISTINCT : SELECT 2개 열 중복 행 제거
SELECT DISTINCT A.POPLTN_SE_CD,
    A.AGRDE_SE_CD
FROM TB_POPTN A;
-- SELECT * : FROM절 내 테이블 모든 열 출력
SELECT *
FROM TB_INDUTY_CL_SE A;
-- ALIAS : 대체 이름 지정
SELECT A.INDUTY_CL_CD AS 업종분류코드,
    A.INDUTY_CL_NM AS 업종분류명,
    A.INDUTY_CL_SE_CD AS 업종분류구분코드,
    NVL(A.UPPER_INDUTY_CL_CD, '(Null)') AS 상위업종분류코드
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_CD = 'ICS001';
-- || : 합성 연산자
SELECT SUBWAY_STATN_NO || '-' || STATN_NM || '(' || LN_NM || ')' AS "지하철역번호-역명(노선명)"
FROM TB_SUBWAY_STATN;
-- DUAL 테이블 : 단 1건의 데이터가 저장되어 있고 DUMMY열 1개 존재
SELECT ((1 + 1) * 3) / 6 AS "연산결과 값"
FROM DUAL;