-- COMMIT : 변경사 DB 최종 적용
UPDATE TB_SUBWAY_STATN
SET STATN_NM = '역삼역'
WHERE STATN_NM = '역삼';
COMMIT;
-- ROLLBACK : 변경사항 취소
UPDATE TB_SUBWAY_STATN
SET STATN_NM = '역삼역'
WHERE STATN_NM = '역삼';
ROLLBACK;
-- SAVEPOINT : 변경사항 저장
SAVEPOINT SVPT1; -- SAVEPOINT 1
UPDATE TB_SUBWAY_STATN
SET STATN_NM = '역삼역'
WHERE STATN_NM = '역삼';
SAVEPOINT SVPT2; -- SAVEPOINT 2
UPDATE TB_SUBWAY_STATN
SET STATN_NM = '강남역'
WHERE STATN_NM = '강남';
ROLLBACK TO SVPT2; -- SAVEPOINT 1까지 변경사항으로 되돌림