-- NATURAL JOIN 실습
SELECT DEPT_CD,
    A.DEPT_NM,
    B.EMP_NO,
    B.EMP_NM
FROM TB_DEPT_6_1_6 A
    NATURAL JOIN TB_EMP_6_1_6 8
ORDER BY DEPT_CD;
-- NATURAL JOIN을 INNER JOIN으로 변환
SELECT A.DEPT_CD,
    A.DEPT_NM,
    B.EMP_NO,
    B.EMP_NM
FROM TB_DEPT_6_1_6 A,
    TB_EMP_6_1_6 B
WHERE A.DEPT_CD = B.DEPT_CD
ORDER BY DEPT_CD;