-- 실습환경 준비
CREATE TABLE TB_DEPT_6_1_6 (
    DEPT_CD CHAR(4),
    DEPT_NM VARCHAR2(50),
    CONSTRAINT PK_TB_DEPT_6_1_6 PRIMARY KEY(DEPT_CD)
);
INSERT INTO TB_DEPT_6_1_6 (DEPT_CD, DEPT_NM)
VALUES ('D001', '데이터팀');
INSERT INTO TB_DEPT_6_1_6 (DEPT_CD, DEPT_NM)
VALUES ('D002', '영업팀');
INSERT INTO TB_DEPT_6_1_6 (DEPT_CD, DEPT_NM)
VALUES ('D003', 'IT개발팀');
COMMIT;
CREATE TABLE TB_EMP_6_1_6 (
    EMP_NO CHAR(4),
    EMP_NM VARCHAR2(50),
    DEPT_CD CHAR(4),
    CONSTRAINT PK_TB_DEPT_6_1_6 PRIMARY KEY(EMP_NO)
);
-- NATURAL JOIN 실습
SELECT DEPT_CD,
    A.DEPT_NM,
    B.EMP_NO,
    B.EMP_NM
FROM TB_DEPT_6_1_6 A
    NATURAL JOIN TB_EMP_6_1_6 8
ORDER BY DEPT_CD;
-- NATURAL JOIN을 INNER JOIN으로 변환
SELECT A.DEPT_CD,
    A.DEPT_NM,
    B.EMP_NO,
    B.EMP_NM
FROM TB_DEPT_6_1_6 A,
    TB_EMP_6_1_6 B
WHERE A.DEPT_CD = B.DEPT_CD
ORDER BY DEPT_CD;