-- 3개의 테이블 조인 (오라클 방식)
SELECT A.SUBWAY_STATN_NO,
    A.LN_NM,
    A.STATN_NM,
    B.BEGIN_TIME,
    B.END_TIME,
    C.TK_GFF_SE_NM,
    B.TK_GFF_CNT
FROM TB_SUBWAY_STATN A,
    TB_SUBWAY_STATN_TK_GFF B,
    TB_TK_GFF_SE C
WHERE A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO
    AND A.SUBWAY_STATN_NO = '000032'
    AND B.BEGIN_TIME = '0000',
    AND B.END_TIME = '0900'
    AND B.TK_GFF_SE_CD = C.TK_GFF_SE_CD
ORDER BY B.TK_GFF_CNT;
-- 3개의 테이블 조인 (ANSI 표준 방식)
SELECT A.SUBWAY_STATN_NO,
    A.LN_NM,
    A.STATN_NM,
    B.BEGIN_TIME,
    B.END_TIME,
    C.TK_GFF_SE_NM,
    B.TK_GFF_CNT
FROM TB_SUBWAY_STATN A
    INNER JOIN TB_SUBWAY_STATN_TK_GFF B ON (A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO)
    INNER JOIN TB_TK_GFF_SE C ON (B.TK_GFF_SE_CD = C.TK_GFF_SE_CD)
WHERE A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO
    AND A.SUBWAY_STATN_NO = '000032'
    AND B.BEGIN_TIME = '0000',
    AND B.END_TIME = '0900'
    AND B.TK_GFF_SE_CD = C.TK_GFF_SE_CD
ORDER BY B.TK_GFF_CNT;