-- CROSS JOIN - 조인 조건 없는 방식
SELECT ROWNUM AS RNUM,
    NVL(A.DEPT_CD, '(Null)') AS A_DEPT_CD,
    NVL(A.DEPT_NM, '(Null)') AS A_DEPT_NM,
    NVL(B.EMP_NO, '(Null)') AS B_EMP_NO,
    NVL(B.EMP_NM, '(Null)') AS B_EMP_NM,
    NVL(B.DEPT_CD, '(Null)') AS B_DEPT_CD
FROM TB_DEPT_6_1_10 A,
    TB_DEPT_6_1_10 B
ORDER BY RNUM;
-- CROSS JOIN - ANSI 표준 방식
SELECT ROWNUM AS RNUM,
    NVL(A.DEPT_CD, '(Null)') AS A_DEPT_CD,
    NVL(A.DEPT_NM, '(Null)') AS A_DEPT_NM,
    NVL(B.EMP_NO, '(Null)') AS B_EMP_NO,
    NVL(B.EMP_NM, '(Null)') AS B_EMP_NM,
    NVL(B.DEPT_CD, '(Null)') AS B_DEPT_CD
FROM TB_DEPT_6_1_10 A
    CROSS JOIN TB_DEPT_6_1_10 B
ORDER BY RNUM;