-- UNION 연산
SELECT A.INDUTY_CL_CD AS 업종분류코드
FROM TB_INDUTY_CL A
WHERE A.INDUTY_CL_SE_CD = "ICS001"
    AND A.INDUTY_CL_CD = "Q"
UNION
SELECT A.UPPER_INDUTY_CL_CD AS 상위업종분류코드
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_SE_CD = "ICS002"
    AND A.INDUTY_CL_CD LIKE "Q%";
-- UNION ALL 연산
SELECT A.INDUTY_CL_CD AS 업종분류코드
FROM TB_INDUTY_CL A
WHERE A.INDUTY_CL_SE_CD = "ICS001"
    AND A.INDUTY_CL_CD = "Q"
UNION ALL
SELECT A.UPPER_INDUTY_CL_CD AS 상위업종분류코드
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_SE_CD = "ICS002"
    AND A.INDUTY_CL_CD LIKE "Q%";